### ISSUE TITLE
 Request failed with status code 403

### ISSUE THREAD

**Issue by louanfontenele** [mateusbertan/operagx-nitro-generator#1]
Dando esse erro bro, consegue resolver?

![image](https://github.com/mateusbertan/operagx-nitro-generator/assets/2886066/81f2cb7d-3521-4b3f-8fa3-c507ef2a01ff)

**Comment by mateusbertan** [comment]
Boa noite, desculpa a demora para responder, acabei não olhando o GitHub esses últimos dias.

Corrigi o erro, agora tá tudo funcionando de novo! O Discord tinha mudado algumas coisas da API que gera os links, e aí tive que atuatizar no código.

**Comment by louanfontenele** [comment]
> Boa noite, desculpa a demora para responder, acabei não olhando o GitHub esses últimos dias.
> 
> Corrigi o erro, agora tá tudo funcionando de novo! O Discord tinha mudado algumas coisas da API que gera os links, e aí tive que atuatizar no código.

Muito obrigado
